<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>RIB</string>

	<key>scopeName</key>
	<string>source.rib</string>

	<key>fileTypes</key>
	<array>
		<string>rib</string>
	</array>

	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#.*)$\n?</string>
		</dict>
	</array>
</dict>
</plist>
